version: '3'
services:
  api:
    build: ./request-api
    image: api:latest
    ports:
      - "3000:3000"
  database:
    build: ./database
    image: database:latest
    ports:
      - "5432:5432"
    volumes:
      - /var/postgresql/data:/var/lib/postgresql/data
  backend:
    build: ./backend
    image: backend:latest
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:postgresql://database:5432/postgres
      - api.host=api
  frontend:
    build: ./frontend
    image: frontend:latest
    ports:
      - "4000:4000"
    environment:
      -  BACKEND_HOST=backend