FROM python:latest

# Set the application directory

# Install our requirements

# Copy our code from the current folder to /app inside the container

# Make port 3000 available

# Define our command to be run when launching the container
